Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Este algoritmo vai apresentar o antecessor, de um numero usuario
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2024
Var
    numero,antecessor,sucessor: inteiro


Inicio
escreval("digite um valor inteiro: ")
leia(numero)
antecessor := numero - 1
escreval("O antecessor de ", numero, " é ", antecessor)


Fimalgoritmo